{"uuid": "c2ba8e7a-6494-4a2b-997f-588501de024f", "children": ["94b898bc-d770-4447-b52b-b385a1ae24a9"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <a class=\"AppHeader_header__link__3D_hX\" href=\"/account\"> is not clickable at point (1168,44) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\conftest.py\", line 25, in login\n    WebDriverWait(driver, 12).until(EC.presence_of_element_located(PersonalAccountLocators.BUTTON_LK), message=f'Not found locator').click()\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\user\\Documents\\Яндекс\\Diplom\\Diplom_2\\Diplom_3\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1724618979189, "stop": 1724618982321}], "start": 1724618979189, "stop": 1724618983607}